apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
spec:
  ports:
  - name: "http"
    port: 5000
    protocol: TCP
    targetPort: 5000    
  selector:
    app: registry
  type: ClusterIP
